### ISSUE TITLE
Issue about Page developer/AutomatedTasks/TestingEnvironment.adoc

### ISSUE THREAD

**Issue by gymad** [salesagility/SuiteDocs#111]
#### Page with Issue

After te robo configuration an error message appear:
`➜  Configure Test Environment Complete
ERROR: Directive 'track_errors' is deprecated 
in Unknown:0
`

**Comment by pgorod** [comment]
@gymad did you ever get this solved? I have no idea of what is the correct fix for this...

**Comment by Dillon-Brown** [comment]
@pgorod I don't think this is an issue anymore, I can't replicate on PHP 7.2 and the Robo lib doesn't contain track errors. If there is a track_errors issue it will be in one of the libs (Smarty/Zend).

**Comment by pgorod** [comment]
Ok thanks I will close, then.

Speaking of Robo, and linking to that other issue this morning about pulling the necessary files to run tests, do you think we could/should script it a bit? So that people could have the normal zip package, but then decide to set up git or codeception and we would pull things for them. 

(I am not sure how difficult this is, I am just asking if it sounds feasible to you. within our time constraints).

**Comment by Dillon-Brown** [comment]
@pgorod It might be difficult to do it reliably. It's possible to pull down single files from Git but we would first need to detect what version of SuiteCRM they are using and then try and pull down just the missing files from that tag to run the tests (codeception.yml and tests directory), this would be assuming that we don't require more files later and that the test structure stays the same which is unlikely.

This would also be assuming that they have run composer update without the --no-dev flag so that they can even run robo in the first.

**Comment by pgorod** [comment]
Ok, you're right. Thanks!
