### ISSUE TITLE
Screen-capture missing screenshots

### ISSUE THREAD

**Issue by FinnT97** [salesagility/SuiteDocs#21]
Below is a list of all of the sections that have screenshots that need updated:

- Managing User Accounts > Themes tab is no longer there 
- User Interface > Advanced Module Search – There is no ‘Layout Options’ panel 
- Campaign > Campaign ROI Tracking – ROI graph needs updated 
- Sales > PDF Templates  
- Sales > Generate Letter
- Workflow > Send Email – Record Email 
- Workflow > First example WorkFlow 
- Workflow > Process Audit 
- Cases with Portal > Installation & Configuration 
- Cases with Portal > Using AOP 
- Events > Updated Delegate Status 

Once the screenshots have been taken you can drop them in to the directory: 

**SuiteDocs > static > images > en > user**
  
Feel free to change the image titles where appropriate too.

**Comment by pgorod** [comment]
- Managing User Accounts > Themes Tab
This is now in the Advanced tab, Layout options. The text will probably need to be adjusted to reflect the new "Sub-themes" of SuiteP: Dawn, Dusk, Day, Night

- User Interface > Advanced Module Search
just remove this image, the other ones already include the functionality described here. Please revise the text in this section to check if it fits the images, though. This filter function has changed significantly since the time of writing this old documentation.

- Core Modules > Campaign ROI Graph
- Advanced Modules > PDF Templates
- Advanced Modules > Generate Letter
For these three, you can just leave the old images, the new ones wouldn't be significantly different.

- Advanced Modules > Send Email
This image should be straightforward to obtain, just like the one above it. If you don't see a "record Email" option in the Dropdown list, then try to play with the other options on the top of the workflow to see if it makes the option available. Specifically, try changing `Workflow module` to a module that includes email like `Contacts`, set `Run` to `Only on save` and `Run on` to `New Records`. You may have to Save the Workflow after making these settings, and then try creating a new Action.

- Advanced Modules > Workflow
What exactly is the difficulty you're getting here?

- Advanced Modules > Process Audit
You can just leave the old images, the new ones wouldn't be significantly different.

- Advanced Modules > Installation & Configuration
I was going to tell you to leave the old image there, but I don't want an image saying "SugarCRM" :-)
Can you ask around at the office if anybody can get you a screenshot of a Joomla Portal login page?

    Advanced Modules > Using AOP
I'd say we just use the old images here. Maybe an exception is the menu (that row of blue buttons), it would be nice to update that one. Here it is, you just need to add the red border:
![row](https://user-images.githubusercontent.com/15945027/34855177-3752b05e-f736-11e7-8231-368d74666842.jpg)

- Advanced Modules > Sending Invites to Delegates
Use the old image.

- Advanced Modules > Charts
Use the old image

- Advanced Modules > Reports Charts Dashlets
Create a report, any report with a chart, call it `Opportunity Amount Sales Stage`
Go to homepage, click to add dashlet, add a `Reports` dashlet
On that dashlet, click the `pencil´ icon to edit it, tick the checkbox (take a screenshot)
Use this photo-shopped image for the other one: :-)
![report](https://user-images.githubusercontent.com/15945027/34855500-eb740398-f737-11e7-9d7e-11d76ed6900c.jpg)

- Advanced Modules > Scheduled reports
It's a pity that there's a typo in the current screenshots, with that red wavy line of the spell-checker...
For the missing screenshot, just remove it. The text is enough to convey the message.

Thanks!

**Comment by FinnT97** [comment]
Got all of those completed. These are the only screenshots remaining:

- Managing User Accounts > Themes Tab
This is now in the Advanced tab, Layout options. The text will probably need to be adjusted to reflect the new "Sub-themes" of SuiteP: Dawn, Dusk, Day, Night
_Someone else more familiar with the software will probably need to write this_

- Core Modules > Campaign ROI Graph

- Advanced Modules > PDF Templates

Advanced Modules > Workflow
What exactly is the difficulty you're getting here?
_When I'm adding paramaters to the WorkFlow action, I'm unable to select "Duration" to complete the formula_
