### ISSUE TITLE
Dangerous permissions on Page admin/installation-guide/Downloading 

### ISSUE THREAD

**Issue by MorrisR2** [salesagility/SuiteDocs#275]
#### Page with Issue
https://docs.suitecrm.com/admin/installation-guide/downloading-installing/

#### What is wrong, less clear, or missing
The currently suggested chown and chmod specifies that:

Any visitor to the web site (www-data, nobody)
has permission to write (create new files or edit existing files)
ANYWHERE in the SuiteCRM directory
And these directories have executable code.

In other words, any visitor to the site is permitted to run any code they want.

This is, of course, just about the worst security mistake one could possibly make.

#### Proposed fixes and/or additions
Only those files that must be changed by the script should be writeable by the script (the config file?).

Files that are writeable must be in a directory where they are not executable (.htaccess disable PHP).

Similarly, if the script must create new files in a data directory, running PHP from that directory must be disabled.  (Use .htaccess in the *parent* of the data directory).

I will perform an install and attempt to set the minimal required permissions (the correct permissions) and document them.

After initial configuration, the config file should be chnod to be non-writeable.

**Comment by pgorod** [comment]
I know about things that can be improved on the permissions handling (and not just in the Documentation), but I don't think your description accounts for the full breadth of directories that can need write access in SuiteCRM, or for the full breadth of different hosting situations (and limitations) in our real-world scenarios out there.

But first I am curious about your assumptions: 

> Any visitor to the web site (www-data, nobody)
> has permission to write (create new files or edit existing files)
> ANYWHERE in the SuiteCRM directory

If the web server can write to a directory, how does this translate to _the visitors_ writing to that directory? It's only SuiteCRM code that is there to be executed, not random code injected by visitors.

In other words: name one specific attack vector that you can find in the code, with the current permissions recommendations.

**Comment by raymorriscbre** [comment]
> I don't think your description accounts for the full breadth of directories that can need write access in SuiteCRM

That may be true. It's not obvious what all files can be changed via the browser, by people visiting the site.  That may itself be a problem. One solution sometimes used to figure out what permissions are actually needed, beyond what you can readily determine, is known the "scream test".

It may be useful to distinguish between *permissions* to access / modify a file and *mechanisms*.
To actually modify a file, one needs both.  "chmod 666" gives everyone *permission* to write to a file.  Nano provides one mechanism to do so. 

Why isn't "user can modify files they aren't supposed to modify" reported as a security issue in nano?  Notepad doesn't keep track of which files you are allowed to change.   It's not a security issue in Notepad because it's not Notepad's job to decide who is allowed to access what. That's the job of the permissions system, in security terms the "reference monitor".  We would be doing things completely backward if we said "we'll give everyone permission to wipe out any files they want, or upload any code they want, and just hope that they can't find a mechanism to do so".  Yet that's precisely what the current installation doc suggests.  Grant everyone write access to everything and hope that they don't figure out any of the many ways to use that permission.

To give a SuiteCRM-specific example of mechanism versus permission, the upload module is a mechanism.  It doesn't check permission.  It doesn't check that files are safe before accepting them and writing them to disk. There's no whitelist of allow file types, no malware scanning in SuiteCRM.  There is a very short blacklist of four or five *obviously* very dangerous file types, but you can upload a .php7 or .sh file and Suite won't stop you.  Then you can run it - and use it to overwrite the entire installation.


> It's only SuiteCRM code that is there to be executed, not random code injected by visitors.

A) You're certain that SuiteCRM code has way for users to upload or modify any files, either intentional or accidental?  You're wanting to hope that there are no security issues in SuiteCRM, and there never will be?  Bad news - I've got several in the queue to submit right now.

B) You're claiming that you know every server that has SuiteCRM installed has no other code?

C) As I mentioned, user can indeed upload php 7 code.

> In other words: name one specific attack vector that you can find in the code

Policy is that we don't post attack vectors publicly here.  Of course that doesn't mean they aren't posted in violation of policy.  For example, this one was posted this week:https://github.com/salesagility/SuiteCRM/issues/7278

  I'm sending a number of new ones to security@, which is the proper process.

**Comment by connorshea** [comment]
I've previously tried to add similar permissions restrictions to my own instance of the CRM, but they didn't work for a few reasons:
- Generally speaking the biggest problem I've found is that the Repair functionality in the Admin panel (if I remember correctly) modifies a lot of files outside the directories/files you specify here. There's currently no equivalent CLI command for repairing (see also https://github.com/salesagility/SuiteCRM/pull/6793), so removing/disabling this functionality isn't currently viable, and you could end up with a broken CRM. 
- The upgrade process, until recently, also didn't have a CLI equivalent and had to be done through the Admin panel, and that touched files in almost every directory of the CRM.

I definitely agree that this is a problem that needs to be solved, though.

**Comment by connorshea** [comment]
>In other words: name one specific attack vector that you can find in the code, with the current permissions recommendations.

@pgorod for the sake of argument, I don't think this is a valid assumption. Simply because there aren't any specific known vulnerabilities doesn't mean that there aren't any vulnerabilities. We may not know of any vulnerabilities _right this second_, but there have been plenty of vulnerabilities in the past and I'd say it's a safe assumption to make that there are plenty more still to be found, or that will be introduced in the future.

All software has vulnerabilities, Chrome, Firefox, Linux, Windows, etc. IMO preventing/fixing the vulnerabilities themselves is only half the goal, preventing damage when those vulnerabilities occur should also be prioritized.

**Comment by pgorod** [comment]
Both of you take my questions to be claims, which they aren't. 

The overstated claim made in this issue (that everybody can just upload code and execute it) is unproven until a specific report comes in. That's my only claim. I will be quite thankful when the report comes in and proves it - that's an open-source community working well to improve security together - cool.

I don't claim that the opposite is true, that there is no way to attack our app, or that we don't need to do anything, as you can tell if you re-read my post. I know that things need changing, I know that we must work to minimize any opportunities for wrongdoers, even if today we only know half of what it takes to exploit. Tomorrow somebody might discover the other half, that is absolutely correct. Still, that needs to be stated like it is (thus my questions), not overstated. Frankly, I can only tell that he knows what he's talking about from the second post, not from the original issue text.

When SuiteCRM uploads files, it removes their extension (so the web server won't see PHP files), and it sets lower permissions on them. So the whole thing about executing uploaded files is already taken care of. Can it be improved? Sure...

But ok, at this point we really don't need to be confrontational - I understand @raymorriscbre knows his theory, I understand what his claims are, now that they have been more carefully explained (thank you), and I eagerly and thankfully await the specific security reports sent privately via email.

Let me also elaborate on my hesitations:

a. What Connor said - there are more parts of this app that rely on the ability to write to files. We can't afford to recommend permissions settings that break the app. This is a huge codebase that was written by other people. Nobody knows all of it in depth, so this needs to be studied with care.

b. These instructions are very often used by clueless "sysadmins". I can't begin to tell you how much time I've spent on the Forums getting people to set permissions so they can install the app. Many of them never typed a command on a Linux shell before. Sometimes it takes me a back and forth of 15 posts just to get people to determine which user their web server is running under. Other times it's the shared hostings that don't let them change necessary settings.

As I am thinking where we should go from here, I believe we might need a simple, basic set of newbie instructions, and then a separate page for hardening security, written for sysadmins who are _not_ clueless.

**Comment by Dillon-Brown** [comment]
Hi @MorrisR2 @raymorriscbre, I don't think I really disagree with anyone here. Yes, we should have more restrictive permissions but at the moment that would mean at the very least foregoing the use of studio and quick repair & rebuild and would likely just stop the app from working entirely. 

If an actual attack could be demonstrated (And reported to the security email) as mentioned by the OP as "In other words, any visitor to the site is permitted to run any code they want." then we should, of course, consider this an immediate high impact security issue to be fixed for the next security release.

In the mean-time, I think this would be more appropriately considered as a backlog task along the lines of "Security Hardening" with other ongoing general security hardening work in SuiteCRM. Of course, I'm open to discussion on this issue if you disagree or just want to discuss this further either here or in the [developer chat](https://gitter.im/suitecrm/Lobby).

**Comment by connorshea** [comment]
@pgorod @Dillon-Brown sorry for not replying sooner.

I agree it's not an easy change to make, and would require disabling Studio, most of the admin panel, and probably a bunch of other functionality that currently assumes write-access for the local filesystem by the web process. It'd also require command line alternatives to be provided for all of these.

I think a separate page of documentation on the security hardening options is definitely a good idea. :)

**Comment by MorrisR2** [comment]
@pogorod said "I understand @raymorriscbre knows his theory ..."

Indeed I do NOT know SuiteCRM well at all, I DO have 20 years of full time web security experience. I know how to secure things and what the most common security issues are, as well as the most severe security issues. I don't know what it will take to fix the most severe issues in SuiteCRM.

I've been meaning to run the existing Selenium-based tests, with only a limited set of directories set to be world-writeable, but haven't gotten a chance to set that up.

I would assume that "most of the admin panel" writes to predictable data directories / files?  That would be standard practice even for Matt's script archive, "PHP for Dummies" level stuff, so I assumed that only a few functions would write outside of the designated places.  I hope Connor isn't saying that "most of the admin panel" writes stuff all over the place?

If my assumption is wrong, if there are no designated directories for data, no particular place uploaded files end up, and most of the functionality requires that everything is world writeable, fixing all that could be quite an undertaking indeed. I'm hoping that's not the case, that there is some degree of discipline or predictability about where the software writes data.

If it's not predictable or controlled, perhaps fixing SuiteCRM isn't a reasonable goal after all. We would just have to mark a company as failing / non-compliant if they have SuiteCRM installed at all, if in fact there's no reasonable hope of controlled or predicting where it can write to the filesystem and what can be uploaded.

**Comment by pgorod** [comment]
I think we could probably drop the world-writable immediately, and make our recommended permissions 750 and 770. I don't see that this would hurt anything. Working installations would keep working, and not-working ones would still not work. When the ownerships are set correctly, that part of the permissions simply will not be used.

The rest, we should just change incrementally, so it can be properly tested (automated tests are not enough, they don't have enough coverage).

About the directories that get written to, they are _somewhat_ specified. I would say that the SugarCRM guys typically made reasonably good designs, but then the codebase seems to always include exceptions and stuff that completely disregards the designs. Hopefully this isn't too extensive and can be tackled incrementally.

There are a couple of reasons why I think the current situation is less grave that it might seem:

- the maturity of this codebase. It's been going on for years, it gets a lot of attention from a lot of developers, it's been through security audits, it has received priority treatment of any reported security issues for years. 

- about the difference explained above between "mechanism versus permission": we can live with wider permissions because we have done extensive checking of said mechanisms. We shouldn't rest on this, like we're not worried, because something more could be discovered tomorrow, that is true. But we also don't need to freak out like our servers are just waiting to be exploited. They aren't.

- as I mentioned above, the permissions are changed by the app itself during execution, so the installation permissions don't mean that everything in those directories will get the same permissions. This procedure needs a few fixes that I know of, though. 

Going forward, I believe the only appropriate way of dealing with this is: security experts kindly alert us to stuff that we might not be noticing; we come in with our SuiteCRM expertise and understanding of how the program works; from the combinations of these two elements of knowledge, nice improvements will take place. These should be immediate for critical vulnerabilities, and incremental for generic, currently unexploitable concerns.

**Comment by raymorriscbre** [comment]
Thanks pgorod.  I'm hoping I get time to work with you and other Suite developers. It sounds like there is more to be done than I initially expected. Specifically "reasonably good designs, but then the codebase seems to always include exceptions and stuff that completely disregards the designs". I certainly understand that.

One effective way to handle that is the "rip the bandaid off" technique, also called the scream test. Set writeable permissions only on the designated writeable data directories, according to the "reasonably good design".  When "stuff that completely disregards the designs" breaks, fix it to write to the proper place.  That's painful in the short term, but prevents long term pain.  In particular, it prevents the problem getting worse over time because people keep introducing more code that writes to who-knows-where.  That's a problem with the "slowly fix all of the code, then fix the permissions" approach - exceptions and things that disregard the design can be introduced faster than they are being fixed, unless permissions prevent new code issues from being introduced.  Sometimes ripping the bandaid off quickly hurts a lot less than slowly peeling it.

**Comment by pgorod** [comment]
I basically agree with you, the only problem is that automated tests are not enough (currently) and if we get a feeling that "breaking something" has a real risk of not being detected before release (and it does...) then out of respect for our users we need to take things very carefully. This is a big and complex piece of software.

But this conversation did stir in me the will to go and try a few permissions tests, let's hope I can find the time. Thanks.

**Comment by pgorod** [comment]
Requests for new Documentation will now be tracked in a master list at #444.

Individual requests such as this Issue will be closed, but don't worry, the list will still reference the request - it's just a different way of managing the Issue list.
