### ISSUE TITLE
Missing semicolon in an example in Advanced Configuration Options.adoc

### ISSUE THREAD

**Issue by TLii** [salesagility/SuiteDocs#324]
#### Page with Issue

https://docs.suitecrm.com/admin/advanced-configuration-options/
#### What is wrong, less clear, or missing

Under the topic _Subpanels: replacing the drop-down menu with buttons_, the given example statement is missing a trailing semicolon. Even though it's only an example, it isn't syntactically correct and should be fixed.

#### Proposed fixes and/or additions

The code should read:

`$layout_defs['Leads']['subpanel_setup']['history']['flat'] = 1;
`

**Comment by pgorod** [comment]
Hi @TLii, thanks for this! I was away on a long vacation so I am only looking at this now. 

Do you think you could just make the edit yourself? I like to encourage users to edit the site, because that is the concept of our community work here: it a wiki-style site, very easy to edit. 

It should take you less time to fix this small detail than it took you to write the text in this issue explaining ;-)

Here is a tutorial: https://docs.suitecrm.com/community/contributing-to-docs/simple-edit/

**Comment by pgorod** [comment]
Ok I fixed this myself. Thanks.
