### ISSUE TITLE
We can't use the latest Hugo versions

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteDocs#342]
Subj.

The last working version is 0.54.

I propose to update the Learn theme to version [2.4](https://github.com/matcornic/hugo-theme-learn/releases/tag/2.4.0).

**Comment by pgorod** [comment]
Hi @likhobory 

Although this would be nice, I've been delaying it, because it's not as easy as it seems. When we adopted the Theme we didn't keep our customizations completely separate from the Theme - I just didn't understand Hugo sufficiently back then. 

To upgrade, I will have to first do a "clean" separation, so that all our customizations are not in the Theme directory. It's only one or two days' work, but I am busy working on the Forums migration to Discourse, which is long delayed and is a higher priority.

So this will be the plan:
- make Netlify use Ubuntu 16.04 instead of 14.04 (we ran into a few problems with that)
- separate cleanly the Theme customizations
- upgrade Theme
- upgrade Hugo
