### ISSUE TITLE
Issue about Page admin/installation-guide/Using the Upgrade Wizard.adoc

### ISSUE THREAD

**Issue by marcovansteen** [salesagility/SuiteDocs#467]
#### Page with Issue

https://docs.suitecrm.com/admin/installation-guide/using-the-upgrade-wizard/

#### What is wrong, less clear, or missing
The layout is deleted by design during this process. Most css is gone, all crm pages become barely usable.
#### Proposed fixes and/or additions
Hints on how to restore the system to a usable state are necessary.

**Comment by pgorod** [comment]
> he layout is deleted by design during this process. Most css is gone, all crm pages become barely usable.

Why do you say this is "by design"? It isn't. 

What you're seeing (unless it is solvable by a QR & R) is typical of systems that don't have their ownnerships/permissions set correctly.

My advice is to open a thread in the Forums and give more details about your configuration, and try to get things right - you'll get some help there (possibly from me!). This isn't a documentation issue. Thanks.
