### ISSUE TITLE
Issue about Page admin/installation-guide/Downloading 

### ISSUE THREAD

**Issue by computamike** [salesagility/SuiteDocs#501]
#### Page with Issue
https://docs.suitecrm.com/admin/installation-guide/downloading-installing/

#### What is wrong, less clear, or missing
In section :  _**Copying SuiteCRM files to web server**_ , step 4 has the following 

Set the correct permissions on the SuiteCRM directory (Linux):
```
  sudo chmod 775 config_override.php 2>/dev
```
The zip file download does not contain a `config_override.php` - so executing this line will produce an error.  There seems to be some mentions that this file can be used to  make configuration changes.

#### Proposed fixes and/or additions
- Remove this line from the installation instructions
- Suggest that a skeleton `config_override.php` be shipped, allowing these instructions to operate as is
- Add a step in the installation instructions to add or create a `config_override.php` - I've not tested this - but a 'touch config_override.php` might a solution

**Comment by pgorod** [comment]
If you use the full command it ends with **/dev/null**, not just **/dev**.

And that part is there specifically so that it doesn't show an error if the file is not present. It redirects the error output into a dummy, null file.

The reason it was added is because many people use that set of commands repeatedly, not just on installation, and this was a way of making it work both for new installs and all other circumstances.

**Comment by computamike** [comment]
@pgorod Whoops.... I missed that.  Thanks for letting me know...
