### ISSUE TITLE
Issue about Page user/modules/PasswordManagement.adoc

### ISSUE THREAD

**Issue by allandelivery** [salesagility/SuiteDocs#607]
#### When i set the **TWO-FACTOR** AUTENTICATION in my user with admin privileges to YES, the application **stopped working**.

The page showed this **warning**:

"Error occurred while fetching data"

![image](https://user-images.githubusercontent.com/132698226/236531930-1645ac0a-721f-4261-be32-a151908e4bd7.png)

I some how received the code emails, but the application didn't show the page to put the code and enter. 

After i set the two-factor, i logged one or two times with success using it, after that the warning was shown.

I had to go to the database, and change the value of factor_auth in users table. Set to 0 for the admin, and then the application come back to live.
[MYSQL]> USE <databasename>;
[MYSQL]> UPDATE users SET factor_auth=0;

Anyone with the same issue?
Maybe its a glitch?

Wait your reply to set two-factor again.

my regards.

**Comment by pgorod** [comment]
Hi

you created an issue in the documentation repository, this is meant for updates to the Documentation itself.

Your issue is adequate to the Community Forums, please post there instead, and close this issue here.

https://community.suitecrm.com/

Thanks!

**Comment by johnM2401** [comment]
Hey Folks!

I'll close this off now. 
As @pgorod mentioned, this repo is moreso for issues/additions to the Documentation itself, rather than issues with the CRM functionality.

However, if you're still having issues and cannot find assistance on the Community Forums, you can raise a bug in the following Repos:

Suite8: https://github.com/salesagility/SuiteCRM-Core/issues 
Suite7: https://github.com/salesagility/SuiteCRM/issues

Please provide any information possible, such as: PHP Version/SuiteCRM Version/ Steps to replicate

Thanks!
(and thanks again @pgorod for your time/efforts!)
