### ISSUE TITLE
Code help iPod

### ISSUE THREAD

**Issue by diogojoaquim** [salesagility/SuiteDocs#665]

**Comment by johnM2401** [comment]
Hey!
Thank you for getting in touch!

I'm closing this off for now, due to lack of information.

However, If you need assistance with the coding of features/functionality, the best places to check would be the community forums or the Documentation:
https://community.suitecrm.com/
https://docs.suitecrm.com/

Otherwise, if you have issues *with* the documentation site itself (or its contents), please get back in touch here (or raise another issue) with further information.

Thank you again!
